window.APP_DATA = function() {
  return {
    character: createDefaultCharacter('shaman'),
    classData: CLASS_DATA,
    statKeys: STAT_KEYS,
    statIcons: STAT_ICONS,
    equipmentSlots: [
      { key: 'head',      label: 'Cabeza',   icon: '🪖', extraFields: [{ key: 'defense', label: 'Defensa', icon: '🛡️' }] },
      { key: 'chest',     label: 'Pecho',    icon: '🛡️', extraFields: [{ key: 'defense', label: 'Defensa', icon: '🛡️' }] },
      { key: 'hands',     label: 'Manos',    icon: '🧤' },
      { key: 'legs',      label: 'Piernas',  icon: '👖' },
      { key: 'feet',      label: 'Pies',     icon: '🥾' },
      { key: 'mainHand',  label: 'Mano Fuerte', icon: '⚔️', extraFields: [{ key: 'weaponDamage', label: 'Daño', icon: '💥' }] },
      { key: 'offHand',   label: 'Mano Débil', icon: '🗡️', extraFields: [{ key: 'weaponDamage', label: 'Daño', icon: '💥' }, { key: 'defense', label: 'Defensa', icon: '🛡️' }] },
      { key: 'twoHand',   label: 'Arma a Dos Manos', icon: '🔨', extraFields: [{ key: 'weaponDamage', label: 'Daño', icon: '💥' }] },
    ],
    showExportModal: false,
    showTalentModal: false,
    hoveredTalent: null,
    showEquipment: false,
    showEffectsPanel: false,
    effectTypes: EFFECT_TYPES,
    buffDebuffStats: BUFF_DEBUFF_STATS,
    statusOptions: STATUS_OPTIONS,
    hotDotTargets: HOT_DOT_TARGETS,
    newEffect: { type: 'buff', name: '', target: 'aguante', value: 0, duration: 1 },
    toastMessage: '',
    xpInputAmount: null,
    levelUpFlash: false,
    turnNumber: 1,
    turnDamage: 0,
    hpLossAmount: null,
    hpLossType: 'magical',
    warriorStance: 'battle',
    warriorWeaponMode: 'twohanded',
  };
};
